### ISSUE TITLE
Memoizer is senseless for now

### ISSUE THREAD

**Issue by magdel** [yandex-money/db-queue#16]
The only Memoizer constructor usage is 
private static <T, U> Function<T, U> memoize(Function<T, U> function) {
            return new Memoizer<T, U>().doMemoize(function);
        }
where instance is lost on method return. So do the cache with it.
You need to keep instance of Memoizer somewhere to get profit.

**Comment by f0y** [comment]
I don't get it. The instance is kept in DURATION_CONVERTER.

**Comment by magdel** [comment]
There you have static method reference instance but not object one.

**Comment by f0y** [comment]
I guess your point is that caching don't work. As for now I cannot agree with you. But after I wrote that code I already saw some flaws. For example, current implementation cannot cache a result of  a transforming function for arbitrary properties. 

I agree that current implementation  must be refactored.

**Comment by magdel** [comment]
Caching is not working definitely, yes, that's the point.
I didn't about solution yet, too

**Comment by f0y** [comment]
Talk is cheap. Show me the code.

P.S. you are wrong 👀

**Comment by magdel** [comment]
The only place to create instance of Memorizer is
 private static <T, U> Function<T, U> memoize(Function<T, U> function) {
            return new Memoizer<T, U>().doMemoize(function);
        }

If reference to Memoizer is not stored so do the cache.
You just create new Memoizer every time and losing it.

**Comment by f0y** [comment]
You want me to write some tests? I've checked this yesterday and the value is cached. So check it out by yourself.

**Comment by magdel** [comment]
Yay, you capture instance in anonymous class. Terrible idea, pretty unobvious. It might be enough to create local var with map and capture it for readability).

**Comment by f0y** [comment]
As I said before caching must be refactored to allow memoizing of arbitrary transforming functions.
